apiVersion: v1
kind: Service
metadata:
  labels:
    run: dotnetapp
  name: dotnetapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: dotnetapp
  type: LoadBalancer